# Generated by Django 5.1.4 on 2024-12-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_driver_id_delete_city_delete_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
